import { useCallback, useEffect, useState } from "react";
import { Clock3, Play, Plus, Save, Timer } from "lucide-react";
import { PageHeader } from "../components/PageHeader";
import { api } from "../lib/api";

type WorkflowDefinition = { start: string; nodes: Array<{ id: string; kind: string }>; edges: Array<{ from: string; to: string; when?: string }> };
type Workflow = { id: string; name: string; description: string; status: "draft" | "active" | "paused" | "archived"; definition: WorkflowDefinition; schedule: { kind: "daily"; at: string; timezone: string } | { kind: "interval"; everySeconds: number } | null; nextRunAt: string | null; lastRunAt: string | null };
const workflowDefinition = (approval = false) => approval ? { start: "start", nodes: [{ id: "start", kind: "trigger" }, { id: "approval", kind: "approval", risk: "B", title: "Approve workflow completion", detail: "Continue this bounded workflow?", expiresInSeconds: 86_400 }, { id: "approved", kind: "notify", message: "Workflow approved" }, { id: "rejected", kind: "notify", message: "Workflow rejected or expired" }], edges: [{ from: "start", to: "approval" }, { from: "approval", to: "approved", when: "success" }, { from: "approval", to: "rejected", when: "rejected" }] } : { start: "start", nodes: [{ id: "start", kind: "trigger" }, { id: "notify", kind: "notify", message: "Automation completed" }], edges: [{ from: "start", to: "notify" }] };

export function CronPage() {
  const [workflows, setWorkflows] = useState<Workflow[]>([]); const [selectedId, setSelectedId] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const result = await api<{ workflows: Workflow[] }>("/workflows"); setWorkflows(result.workflows); setSelectedId((id) => id || result.workflows[0]?.id || ""); }, []);
  useEffect(() => { load().catch((reason) => setError(reason.message)); }, [load]);
  const selected = workflows.find((workflow) => workflow.id === selectedId);
  const create = async () => { setBusy(true); setError(""); setNotice(""); try { const result = await api<{ workflow: Workflow }>("/workflows", { method: "POST", body: JSON.stringify({ name: `Workflow ${new Date().toLocaleString()}`, description: "A durable bounded automation.", enabled: false, schedule: { kind: "daily", at: "09:00", timezone: "UTC" }, definition: workflowDefinition() }) }); setWorkflows((current) => [result.workflow, ...current]); setSelectedId(result.workflow.id); setNotice("Workflow created. Configure it below, then save it."); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const save = async (form: HTMLFormElement) => { if (!selected) return; setBusy(true); setError(""); setNotice(""); const data = new FormData(form); try { const result = await api<{ workflow: Workflow }>(`/workflows/${selected.id}`, { method: "PUT", body: JSON.stringify({ name: data.get("name"), description: data.get("description"), enabled: data.get("enabled") === "on", schedule: { kind: "daily", at: data.get("at"), timezone: data.get("timezone") }, definition: workflowDefinition(data.get("approval") === "on") }) }); setWorkflows((current) => current.map((workflow) => workflow.id === result.workflow.id ? result.workflow : workflow)); setNotice("Workflow saved."); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const start = async () => { if (!selected) return; setBusy(true); try { await api(`/workflows/${selected.id}/start`, { method: "POST" }); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  return <div className="page cron-page v04-page"><PageHeader eyebrow="Phase 7 · durable automation" title="Workflow Studio" description="Schedules and workflow state persist in Orbit. Approval branches wait independently and never reach paper or live trading." actions={<button className="button primary" disabled={busy} onClick={create}><Plus size={15} />New workflow</button>} />
    {error && <div className="phase4-error">{error}</div>}{notice && <div className="phase4-success">{notice}</div>}<div className="cron-layout reveal delay-1"><aside className="cron-list glass-panel v04-surface"><header><span>WORKFLOWS</span></header>{workflows.map((workflow) => <button key={workflow.id} className={workflow.id === selectedId ? "selected" : ""} onClick={() => setSelectedId(workflow.id)}><span className={"cron-state " + (workflow.status === "active" ? "active" : "")}><Timer size={15} /></span><span><strong>{workflow.name}</strong><small>{workflow.nextRunAt ? new Date(workflow.nextRunAt).toLocaleString() : "No active schedule"}</small></span></button>)}</aside>
      {selected && <section className="cron-builder glass-panel v04-surface"><form onSubmit={(event) => { event.preventDefault(); save(event.currentTarget); }}><header className="cron-builder-head"><div><p className="eyebrow"><span />Executable workflow</p><input name="name" defaultValue={selected.name} required /></div><button className="button primary compact" disabled={busy}><Save size={13} />Save</button></header><div className="cron-settings-row"><label><span>Description</span><input name="description" defaultValue={selected.description} /></label><label><span>UTC / IANA timezone</span><input name="timezone" defaultValue={selected.schedule?.kind === "daily" ? selected.schedule.timezone : "UTC"} required /></label><label><span>Daily time</span><input name="at" type="time" defaultValue={selected.schedule?.kind === "daily" ? selected.schedule.at : "09:00"} required /></label><label className="switch"><input name="enabled" type="checkbox" defaultChecked={selected.status === "active"} /><span /></label><label><span>Human approval</span><input name="approval" type="checkbox" defaultChecked={selected.definition.nodes.some((node) => node.kind === "approval")} /></label></div></form><section className="workflow-workbench"><header><div><p className="section-kicker">Workflow schema</p><h3>{selected.definition.nodes.map((node) => node.kind).join(" → ")}</h3></div><span className="status-pill active"><i />{selected.status.toUpperCase()}</span></header><p>The builder emits a validated executable graph. A selected approval creates a durable Human Inbox request with explicit approve, reject, and expiry paths.</p></section><footer className="cron-builder-footer"><span><Clock3 size={14} />Last run: {selected.lastRunAt ? new Date(selected.lastRunAt).toLocaleString() : "Never"}</span><button className="button secondary" disabled={busy} onClick={start}><Play size={14} />Run now</button></footer></section>}</div></div>;
}
