import { ArrowDownRight, ArrowUpRight, Coins, Cpu, Gauge, HardDrive, MoreHorizontal, Sparkles } from "lucide-react";
import { PageHeader } from "../components/PageHeader";

const bars = [22, 28, 18, 36, 42, 34, 49, 57, 44, 62, 70, 54, 68, 76];

export function UsagePage() {
  return <div className="page"><PageHeader eyebrow="Usage intelligence" title="Understand what the system consumes" description="Simulated costs, tokens and load — ready to accommodate real Pi metrics." actions={<button className="button secondary">Ce mois-ci</button>} />
    <section className="usage-metrics reveal delay-1"><article><div className="metric-icon cyan"><Coins size={18} /></div><p>Estimated expense</p><strong>€18.42</strong><em className="positive"><ArrowDownRight size={13} />12% vs juin</em></article><article><div className="metric-icon violet"><Sparkles size={18} /></div><p>Tokens used</p><strong>2.84M</strong><em><ArrowUpRight size={13} />8% this week</em></article><article><div className="metric-icon rose"><Cpu size={18} /></div><p>Temps agent</p><strong>14h 26m</strong><em>42 sessions</em></article><article><div className="metric-icon amber"><HardDrive size={18} /></div><p>Contexte moyen</p><strong>38%</strong><em>Zone optimale</em></article></section>
    <section className="usage-grid reveal delay-2"><article className="usage-chart glass-panel"><div className="panel-heading"><div><p className="section-kicker">Tokens quotidiens</p><h3>Activity from the last 14 days</h3></div><button className="icon-button"><MoreHorizontal size={16} /></button></div><div className="bar-chart"><div className="y-axis"><span>300k</span><span>200k</span><span>100k</span><span>0</span></div><div className="bars">{bars.map((bar,index) => <div key={index}><i style={{ height: `${bar}%` }} className={index === bars.length - 1 ? "active" : ""} /><span>{index % 2 === 0 ? index + 2 : ""}</span></div>)}</div></div></article><article className="model-breakdown glass-panel"><div className="panel-heading"><div><p className="section-kicker">Distribution</p><h3>By model</h3></div></div><div className="donut"><div><strong>€18</strong><span>Total</span></div></div><div className="model-legend"><p><i className="cyan" /><span>Claude Sonnet 4</span><strong>48%</strong></p><p><i className="violet" /><span>GPT-5.4</span><strong>31%</strong></p><p><i className="rose" /><span>Gemini 2.5 Pro</span><strong>14%</strong></p><p><i className="amber" /><span>DeepSeek V3</span><strong>7%</strong></p></div></article></section>
    <section className="optimization-banner reveal delay-3"><span className="summary-icon cyan"><Gauge size={18} /></span><div><strong>Pi recommends optimization</strong><p>Indexing tasks could use a lighter model and reduce the simulated cost by 18%.</p></div><button className="button secondary">Examiner</button></section>
  </div>;
}
